export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  IDEMPOTENCY_KEY_REUSE = 'IDEMPOTENCY_KEY_REUSE',
  CONFLICT_STATE = 'CONFLICT_STATE',
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  DOWNSTREAM_TIMEOUT = 'DOWNSTREAM_TIMEOUT',
  DOWNSTREAM_UNAVAILABLE = 'DOWNSTREAM_UNAVAILABLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
